# Use the CDN to make CircleCI builds faster.
source 'https://cdn.cocoapods.org/'

# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'FontScreenshotter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FontScreenshotter
  pod 'Haneke', '~> 1.0.2', :inhibit_warnings => true
  pod 'Reachability', '~> 3.2'

  target 'FontScreenshotterUITests' do
    # Pods for testing
  end

end

target 'Tsurukame' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tsurukame
  pod 'Charts', '~> 3.1.0', :inhibit_warnings => true
  pod 'FMDB', '~> 2.7.5'
  pod 'Haneke', '~> 1.0.2', :inhibit_warnings => true
  pod 'Light-Untar', '~> 0.3.0', :inhibit_warnings => true
  pod 'MMDrawerController', '~> 0.6.0', :inhibit_warnings => true
  pod 'OAStackView', '~> 1.0.1'
  pod 'PromiseKit/CorePromise', '6.8.2'
  pod 'PromiseKit/Foundation', '6.8.2'
  pod 'Reachability', '~> 3.2'

  target 'Tests' do
    inherit! :search_paths

    platform :ios, '9.3'
    pod 'Hippolyte', '~> 0.4.0'
  end
end

# Delete the IPHONEOS_DEPLOYMENT_TARGET config setting so it inherits the
# podfile platform setting.
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end